config/routes.rb
Mystore::Application.routes.draw do
  
  match 'orders/:product_id/see_price_in_cart' => "spree/orders#see_price_in_cart", as: :see_price_in_cart

  match 'products/:product_id/out_of_stock_notifier' => "spree/products#out_of_stock_notifier", as: :out_of_stock_notifier

  match 'products/update_states' => "spree/products#update_states", as: :update_states

  match 'admin/products/:product_id/select_products/:taxonomy_id' => "spree/admin/products#select_products", as: :select_products

  match 'admin/products/:taxonomy_id/remove_product_taxons/:product_id' => "spree/admin/products#remove_product_taxons", as: :remove_product_taxons

  match 'admin/products/:product_id/selected_product_taxons' => "spree/admin/products#selected_product_taxons", as: :selected_product_taxons

  match 'admin/products/:taxonomy_id/available_products_for_taxon' => "spree/admin/products#available_products_for_taxon", as: :available_products_for_taxon

  match 'admin/taxons/:taxonomy_id/products_for_selected_taxonomy' => "spree/admin/taxons#products_for_selected_taxonomy", as: :products_for_selected_taxonomy

  get "categories/index"

  get '/update_states' => 'user_registrations#update_states', :as => :update_states
  
  mount Spree::Core::Engine, :at => '/'
	namespace :admin do
        resources :categories
        resources :user_groups
        resources :manufactures
       
    resources :taxonomies do
      member do
        get :get_children
      end

      resources :taxons
    end

    end

match '/admin' => 'spree/admin/taxonomies#index', :as => :admin

match 'admin/reports/products_below_mimimum_quantity' => 'spree/admin/reports#products_below_mimimum_quantity' , as: :products_below_mimimum_quantity

match 'admin/reports/low_stock_report' => 'spree/admin/reports#low_stock_report' , as: :low_stock_report

match 'admin/reports/low_stock' => 'spree/admin/reports#low_stock' , as: :low_stock

match 'admin/reports/customer_report' => 'spree/admin/reports#customer_report' , as: :customer_report

match 'admin/reports/margin_report' => 'spree/admin/reports#margin_report' , as: :margin_report

match 'admin/reports/manufacture_sales_report' => 'spree/admin/reports#manufacture_sales_report' , as: :manufacture_sales_report

match 'admin/reports/referral_source_report' => 'spree/admin/reports#referral_source_report' , as: :referral_source_report

  

end

app/views/spree/admin/taxonomies/_form.html.erb
<div data-hook="admin_inside_taxonomy_form">
  <%= f.field_container :name do %>
    <%= f.label :name, t(:name) %> <span class="required">*</span><br />
    <%= error_message_on :taxonomy, :name, :class => 'fullwidth title' %>
    <%= text_field :taxonomy, :name %>
  <% end %>
</div>

app/views/spree/admin/taxonomies/_js_head.html.erb
<% content_for :head do %>
  <%= javascript_tag "var taxonomy_id = #{@taxonomy.id};
    var loading = '#{escape_javascript t(:loading)}';
    var new_taxon = '#{escape_javascript t(:new_taxon)}';
    var server_error = '#{escape_javascript t(:server_error)}';
    var taxonomy_tree_error = '#{escape_javascript t(:taxonomy_tree_error)}';"
  %>
<% end %>

app/views/spree/admin/taxonomies/_list.html.erb
<table class="index" id='listing_taxonomies' data-hook>
  <tr data-hook="taxonomies_header">
    <th></th>
    <th><%= t(:name) %></th>
    <th></th>
  </tr>
  <% @taxonomies = Spree::Taxonomy.find_by_name('Categories')  %>
  <%# @taxonomies = @taxonomies.taxons.first  %>
  <% if @taxonomies.present? %>
    <% @taxonomy = @taxonomies %>
    <%= render :partial => 'js_head' ,:locals => {:taxonomy => @taxonomy}%>
    <tr id="<%= dom_id @taxonomy %>" data-hook="taxonomies_row">
      <td>
        <div>
          <%= label_tag nil, t(:tree) %><br />
          <div id="taxonomy_tree" class="tree" data-url="<%= admin_taxonomy_taxons_path @taxonomy %>"></div>
        </div>
      </td>
      <td>
        <%= @taxonomy.name %>
      </td>
      <td class="actions">
        <%= link_to_edit @taxonomy.id, :class => 'edit' %>
        &nbsp;
        <%= link_to_delete @taxonomy %>
      </td>
    </tr>
    <% #end %>
  </table>
  <div id="selected-products" data-hook>
    <%= render(:partial => 'product_table', :locals => { :products => @products }) %>
  </div>

  <%= form_tag '#' do %>
    <%= label_tag nil, t(:search) %>:
    <input id="searchtext" size="25">
  <% end %>

  <%= javascript_tag do %>
    
    function search_for_taxons(){
    $.ajax({
    data: {q: $("#searchtext").val(),taxon_id: $("#selected_taxonomy_id").val() },
    dataType: 'html',
    success: function(request){
    jQuery('#search_hits').html(request);
    },
    type: 'POST',
    url: '<%= main_app.available_products_for_taxon_path(@taxonomy.taxons.first, :format => 'js') %>'
    });
    }

    $("#searchtext").keypress(function (e) {
    if ((e.which && e.which == 13) || (e.keyCode && e.keyCode == 13)) {
    search_for_taxons();

    return false;
    } else {
    return true;
    }
    });

    $("#searchtext").delayedObserver(function() {
    search_for_taxons();
    }, 0.75);
  <% end %>
  <br />
  <div id="search_hits" data-hook></div>

  <% content_for :head do %>
    <%= javascript_tag do -%>
      <% @tax=[] %>
      var initial = [
      { "attr" :
      { "id" : "<%= @taxonomy.root.id %>", "rel" : "root" },
      "url": "/google.com",
      "data" : "<%= @taxonomy.root.name %>",
      "state" : "open",
      "children" : [
      <% @tax << @taxonomy.root.id %>
      <% @taxonomy.root.children.each_with_index do |taxon,i| %>
        <% @tax << taxon.id %>
        {
        "attr" :
        { "id" : "<%= taxon.id %>"},
        "data" : "<%= taxon.name %>"
        <% unless taxon.children.empty? %>
          ,"state" : "closed"
        <% end %>
        }<%= ',' if i < (@taxonomy.root.children.size - 1) %>
      <% end %>
      ]
      }
      ];
    <% end -%>
  <% end %>
<% end %>

<%= hidden_field_tag "selected_taxonomy_id" %>
<script>
  var id_val = new Array();
      
  $(window).load(function(){
    $("#taxonomy_tree").children().find('li').each(function(index){
      id_val[index] = $(this).attr("id");
    })
    $("#taxonomy_tree").children().find('a').each(function(index){
      $(this).attr("class", "tree_links");
      $(this).attr("href", "javascript:void(0)");
      $(this).attr("id_val", id_val[index]);


    });

    $(".tree_links").live("click", function(){
      // alert($(this).attr("id_val"));
      $("#selected_taxonomy_id").val($(this).attr("id_val"));
      $.ajax({
        data: {id_val: $(this).attr("id_val") },
        type: 'GET',
        url: '/admin/taxons/'+$(this).attr("id_val")+'/products_for_selected_taxonomy',
        success: function(request){
          //jQuery('#search_hits').html(request);
        }
              
      });
    })

  });


</script>

app/views/spree/admin/taxonomies/_mapped_taxon_products.html.erb
<div>
    <%if taxon %>
    <%= label :from, t(:from) %>
    <%= text_field "taxonomy","from",value: taxon.name , size: 10 ,disabled: :true %>
    <% end %>
    <%if taxon %>
    <%= label :to, t(:to) %>
    <%= select("taxonomy","to", taxon_select, {:include_blank => false}) %>
    <%= link_to icon('add') + ' ' + t(:taxons), '', :id => 'select_taxons_link' ,:remote => false %>
    <% end %>
</div>


<script>
  $(document).ready(function(){
    $('#select_taxons_link').click(function (event) {
      event.preventDefault();
      var taxonomy_from = $("#selected_taxonomy_id").val();
      var taxonomy_to = $('#taxonomy_to').val();
      //$('#selected-products').show();
      $.ajax({type: 'POST',
        url: 'admin/taxons/mapped_taxon_products_copy',
        data: 
        {
          authenticity_token: AUTH_TOKEN,
          taxonomy_from :taxonomy_from,
          taxonomy_to :taxonomy_to
        }      
      });
    });

  });

</script>

app/views/spree/admin/taxonomies/_product_table.html.erb
<table class="index">
  <thead>
    <tr>
      <th><%= t(:sku) %></th>
      <th><%= t(:name) %></th>
    <th><%= t(:master_price) %></th>
    <th><%= t(:action) %></th>
    </tr>
  </thead>
  <tbody>
<h4><%= "Product list mapped with taxonomy" %> - <%= @taxon.name if @taxon %></h4>
    <% if products.blank? %>
     <tr data-hook="taxons_none"><td colspan="3"><%= t(:none) %>.</td></tr>
     <% else %>
    <% products.each do |product| %>
      <tr id="<%= dom_id(product) %>" data-hook="taxons_row">
        <td><%= product.sku rescue '' %></td>
        <td><%= product.name rescue '' %></td>
        <td><%= number_to_currency product.price rescue '' %></td>
        <td class="actions">
          <%= link_to_delete product, :url => main_app.remove_product_taxons_path(@taxon, product), :name => icon('delete') + ' ' + t(:remove) %>
        </td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/taxonomies/_taxon.html.erb
<% if taxon.children.length != 0 %>
  <ul>
    <% taxon.children.each do |child| %>
      <li id="<%= child.id %>" rel="taxon">
        <a style="background-image: url(<%= child.icon.url %>);" href="#"><%= child.name %></a>
        <% if child.children.length > 0 %>
          <%= render :partial => 'taxon', :locals => { :taxon => child } %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/spree/admin/taxonomies/edit.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<%= render :partial => 'js_head' %>

<h1><%= t(:taxonomy_edit) %></h1>

<p id="ajax_error" class="errorExplanation" style="display:none;"></p>

<%= form_for [:admin, @taxonomy] do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <div>
    <%= label_tag nil, t(:tree) %><br />
    <div id="taxonomy_tree" class="tree" data-url="<%= admin_taxonomy_taxons_path @taxonomy %>"></div>
  </div>
  <p id="progress" style="display:none;">
    <%= image_tag 'spinner.gif', :title => 'Spinner', :style => "vertical-align:bottom;" %> <%= t(:updating) %>..
  </p>
  <p><br /><small><%= t(:taxonomy_tree_instruction) %></small></p>


  <p class="form-buttons">
    <%= button t(:update) %> <%= t(:or) %> <%= link_to t(:cancel), admin_taxonomies_path %>
  </p>
<% end %>
<% @taxonomy = Spree::Taxonomy.find(params[:id]) %>
<%@taxon = @taxonomy.taxons.find_by_parent_id(nil)%>
<% @products = @taxon.products %>
<div id="selected-products" data-hook>
  <%= render(:partial => 'product_table', :locals => { :products => @products }) %>
</div>

<% form_tag '#' do %>
  <%= label_tag nil, t(:search) %>:
  <input id="searchtext" size="25" />
<% end %>


<% content_for :head do %>
  <%= javascript_tag do -%>
    var initial = [
    { "attr" :
    { "id" : "<%= @taxonomy.root.id %>", "rel" : "root" },
    "data" : "<%= @taxonomy.root.name %>",
    "state" : "open",
    "children" : [
    <% @taxonomy.root.children.each_with_index do |taxon,i| %>
      {
      "attr" :
      { "id" : "<%= taxon.id %>"},
      "data" : "<%= taxon.name %>"
      <% unless taxon.children.empty? %>
        ,"state" : "closed"
      <% end %>
      }<%= ',' if i < (@taxonomy.root.children.size - 1) %>
    <% end %>
    ]
    }
    ];
  <% end -%>
<% end %>

<script>
  function search_for_taxons(){
    $.ajax({
      data: {q: $("#searchtext").val() },
      dataType: 'html',
      success: function(request){
        jQuery('#search_hits').html(request);
      },
      type: 'POST',
      url: '<%= main_app.available_products_for_taxon_path(@taxonomy, :format => 'js') %>'
    });
  }

  $("#searchtext").keypress(function (e) {
    if ((e.which && e.which == 13) || (e.keyCode && e.keyCode == 13)) {
      search_for_taxons();

      return false;
    } else {
      return true;
    }
  });

  $("#searchtext").delayedObserver(function() {
    search_for_taxons();
  }, 0.75);
    </script>
    <br />
    <div id="search_hits" data-hook></div>

app/views/spree/admin/taxonomies/get_children.json.erb
[<% @taxons.each_with_index do |t,i| %>
  { "attr" :
    { "id" : "<%= t.id %>" },
    "data" : "<%= t.name %>"
    <% unless t.children.empty? %>
      ,"state" : "closed"
    <% end %>
  }<%= "," if i < (@taxons.size - 1) %>
<% end %>]

app/views/spree/admin/taxonomies/index.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<div class="toolbar" data-hook="toolbar">
  <ul class="actions">
    <li>
      <%= button_link_to t(:new_taxonomy), new_admin_taxonomy_url, :icon => 'add', :id => 'admin_new_taxonomy_link' %></p>
    </li>
  </ul>
  <br class="clear" />
</div>

<h1><%= t(:taxonomies) %></h1>

<div id='list-taxonomies' data-hook>
  <%= render :partial => 'list' %>
</div>

app/views/spree/admin/taxonomies/new.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<h1><%= t(:new_taxonomy) %></h1>

<%= form_for [:admin, @taxonomy] do |f| %>

  <%= render :partial => 'form', :locals => { :f => f } %>

  <p class="form-buttons" data-hook="buttons">
    <%= button t(:create) %>
  </p>
<% end %>

app/views/spree/admin/taxonomies/remove_product_taxons.html.erb
<%= render :partial => 'product_table', :locals => { :products => @products } %>