config/routes.rb
Mystore::Application.routes.draw do
  
  match 'orders/:product_id/see_price_in_cart' => "spree/orders#see_price_in_cart", as: :see_price_in_cart

  match 'products/:product_id/out_of_stock_notifier' => "spree/products#out_of_stock_notifier", as: :out_of_stock_notifier

  match 'products/update_states' => "spree/products#update_states", as: :update_states

  match 'admin/products/:product_id/select_products/:taxonomy_id' => "spree/admin/products#select_products", as: :select_products

  match 'admin/products/:taxonomy_id/remove_product_taxons/:product_id' => "spree/admin/products#remove_product_taxons", as: :remove_product_taxons

  match 'admin/products/:product_id/selected_product_taxons' => "spree/admin/products#selected_product_taxons", as: :selected_product_taxons

  match 'admin/products/:taxonomy_id/available_products_for_taxon' => "spree/admin/products#available_products_for_taxon", as: :available_products_for_taxon

  match 'admin/taxons/:taxonomy_id/products_for_selected_taxonomy' => "spree/admin/taxons#products_for_selected_taxonomy", as: :products_for_selected_taxonomy

  get "categories/index"

  get '/update_states' => 'user_registrations#update_states', :as => :update_states
  
  mount Spree::Core::Engine, :at => '/'
	namespace :admin do
        resources :categories
        resources :user_groups
        resources :manufactures
       
    resources :taxonomies do
      member do
        get :get_children
      end

      resources :taxons
    end

    end

match '/admin' => 'spree/admin/taxonomies#index', :as => :admin

match 'admin/reports/products_below_mimimum_quantity' => 'spree/admin/reports#products_below_mimimum_quantity' , as: :products_below_mimimum_quantity

match 'admin/reports/low_stock_report' => 'spree/admin/reports#low_stock_report' , as: :low_stock_report

match 'admin/reports/low_stock' => 'spree/admin/reports#low_stock' , as: :low_stock

match 'admin/reports/customer_report' => 'spree/admin/reports#customer_report' , as: :customer_report

match 'admin/reports/margin_report' => 'spree/admin/reports#margin_report' , as: :margin_report

match 'admin/reports/manufacture_sales_report' => 'spree/admin/reports#manufacture_sales_report' , as: :manufacture_sales_report

match 'admin/reports/referral_source_report' => 'spree/admin/reports#referral_source_report' , as: :referral_source_report

  

end

app/models/spree/order.rb
module Spree
  class Order < ActiveRecord::Base

    attr_accessible :line_items, :bill_address_attributes, :ship_address_attributes, :payments_attributes,
                    :ship_address, :bill_address, :line_items_attributes,
                    :shipping_method_id, :email, :use_billing, :special_instructions

    belongs_to :user
    belongs_to :bill_address, :foreign_key => 'bill_address_id', :class_name => 'Spree::Address'
    belongs_to :ship_address, :foreign_key => 'ship_address_id', :class_name => 'Spree::Address'
    belongs_to :shipping_method

    has_many :state_events, :as => :stateful
    has_many :line_items, :dependent => :destroy
    has_many :inventory_units
    has_many :payments, :dependent => :destroy
    has_many :shipments, :dependent => :destroy
    has_many :return_authorizations, :dependent => :destroy
    has_many :adjustments, :as => :adjustable, :dependent => :destroy

    accepts_nested_attributes_for :line_items
    accepts_nested_attributes_for :bill_address
    accepts_nested_attributes_for :ship_address
    accepts_nested_attributes_for :payments
    accepts_nested_attributes_for :shipments

    # Needs to happen before save_permalink is called
    before_validation :generate_order_number, :on => :create

    before_create :create_user
    after_create :create_tax_charge!

    # TODO: validate the format of the email as well (but we can't rely on authlogic anymore to help with validation)
    validates :email, :presence => true, :format => /^([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})$/i, :if => :require_email
    validate :has_available_shipment
    validate :has_available_payment

    #delegate :ip_address, :to => :checkout
    def ip_address
      '192.168.1.100'
    end

    scope :by_number, lambda { |number| where(:number => number) }
    scope :between, lambda { |*dates| where('created_at BETWEEN ? AND ?', dates.first.to_date, dates.last.to_date) }
    scope :by_customer, lambda { |customer| joins(:user).where("#{Spree::User.table_name}.email = ?", customer) }
    scope :by_state, lambda { |state| where(:state => state) }
    scope :complete, where('completed_at IS NOT NULL')
    scope :incomplete, where(:completed_at => nil)

    make_permalink :field => :number

    class_attribute :update_hooks
    self.update_hooks = Set.new


    # Use this method in other gems that wish to register their own custom logic that should be called after Order#updat
    def self.register_update_hook(hook)
      self.update_hooks.add(hook)
    end

    # For compatiblity with Calculator::PriceSack
    def amount
      line_items.map(&:amount).sum
    end

    def to_param
      number.to_s.to_url.upcase
    end

    def completed?
      !! completed_at
    end

    # Indicates whether or not the user is allowed to proceed to checkout.  Currently this is implemented as a
    # check for whether or not there is at least one LineItem in the Order.  Feel free to override this logic
    # in your own application if you require additional steps before allowing a checkout.
    def checkout_allowed?
      line_items.count > 0
    end

    # Is this a free order in which case the payment step should be skipped
    def payment_required?
      total.to_f > 0.0
    end

    # Indicates the number of items in the order
    def item_count
      line_items.map(&:quantity).sum
    end

    # order state machine (see http://github.com/pluginaweek/state_machine/tree/master for details)
    state_machine :initial => 'cart', :use_transactions => false do

      event :next do
        transition :from => 'cart',     :to => 'address'
        transition :from => 'address',  :to => 'delivery'
        transition :from => 'delivery', :to => 'payment', :if => :payment_required?
        transition :from => 'delivery', :to => 'complete'
        transition :from => 'confirm',  :to => 'complete'

        # note: some payment methods will not support a confirm step
        transition :from => 'payment',  :to => 'confirm',
                                        :if => Proc.new { |order| order.payment_method && order.payment_method.payment_profiles_supported? }

        transition :from => 'payment', :to => 'complete'
      end

      event :cancel do
        transition :to => 'canceled', :if => :allow_cancel?
      end
      event :return do
        transition :to => 'returned', :from => 'awaiting_return'
      end
      event :resume do
        transition :to => 'resumed', :from => 'canceled', :if => :allow_resume?
      end
      event :authorize_return do
        transition :to => 'awaiting_return'
      end

      before_transition :to => 'complete' do |order|
#        raise order.inspect
        begin
          order.process_payments!
        rescue Core::GatewayError
          if Spree::Config[:allow_checkout_on_gateway_error]
            true
          else
            false
          end
        end
      end

      before_transition :to => ['delivery'] do |order|
        order.shipments.each { |s| s.destroy unless s.shipping_method.available_to_order?(order) }
      end

      after_transition :to => 'complete', :do => :finalize!
      after_transition :to => 'delivery', :do => :create_tax_charge!
      after_transition :to => 'payment',  :do => :create_shipment!
      after_transition :to => 'resumed',  :do => :after_resume
      after_transition :to => 'canceled', :do => :after_cancel

    end

    # Indicates whether there are any backordered InventoryUnits associated with the Order.
    def backordered?
      return false unless Spree::Config[:track_inventory_levels]
      inventory_units.backorder.present?
    end

    # Returns the relevant zone (if any) to be used for taxation purposes.  Uses default tax zone
    # unless there is a specific match
    def tax_zone
      zone_address = Spree::Config[:tax_using_ship_address] ? ship_address : bill_address
      Zone.match(zone_address) || Zone.default_tax
    end

    # Indicates whether tax should be backed out of the price calcualtions in cases where prices
    # include tax but the customer is not required to pay taxes in that case.
    def exclude_tax?
      return false unless Spree::Config[:prices_inc_tax]
      return tax_zone != Zone.default_tax
    end

    # Array of adjustments that are inclusive in the variant price.  Useful for when prices
    # include tax (ex. VAT) and you need to record the tax amount separately.
    def price_adjustments
      adjustments = []

      line_items.each do |line_item|
        adjustments.concat line_item.adjustments
      end

      adjustments
    end

    # Array of totals grouped by Adjustment#label.  Useful for displaying price adjustments on an
    # invoice.  For example, you can display tax breakout for cases where tax is included in price.
    def price_adjustment_totals
      totals = {}

      price_adjustments.each do |adjustment|
        label = adjustment.label
        totals[label] ||= 0
        totals[label] = totals[label] + adjustment.amount
      end

      totals
    end

    # This is a multi-purpose method for processing logic related to changes in the Order.  It is meant to be called from
    # various observers so that the Order is aware of changes that affect totals and other values stored in the Order.
    # This method should never do anything to the Order that results in a save call on the object (otherwise you will end
    # up in an infinite recursion as the associations try to save and then in turn try to call +update!+ again.)
    def update!
      update_totals
      update_payment_state

      # give each of the shipments a chance to update themselves
      shipments.each { |shipment| shipment.update!(self) }#(&:update!)
      update_shipment_state
      update_adjustments
      # update totals a second time in case updated adjustments have an effect on the total
      update_totals

      update_attributes_without_callbacks({
        :payment_state => payment_state,
        :shipment_state => shipment_state,
        :item_total => item_total,
        :adjustment_total => adjustment_total,
        :payment_total => payment_total,
        :total => total
      })

      #ensure checkout payment always matches order total
      if payment and payment.checkout? and payment.amount != total
        payment.update_attributes_without_callbacks(:amount => total)
      end

      update_hooks.each { |hook| self.send hook }
    end

    def restore_state
      # pop the resume event so we can see what the event before that was
      state_events.pop if state_events.last.name == 'resume'
      update_attribute('state', state_events.last.previous_state)

      if paid?
        raise 'do something with inventory'
        #Spree::InventoryUnit.assign_opening_inventory(self) if inventory_units.empty?
        #shipment.inventory_units = inventory_units
        #shipment.ready!
      end
    end

    before_validation :clone_billing_address, :if => :use_billing?
    attr_accessor :use_billing

    def clone_billing_address
      if bill_address and self.ship_address.nil?
        self.ship_address = bill_address.clone
      else
        self.ship_address.attributes = bill_address.attributes.except('id', 'updated_at', 'created_at')
      end
      true
    end

    def allow_cancel?
      return false unless completed? and state != 'canceled'
      %w{ready backorder pending}.include? shipment_state
    end

    def allow_resume?
      # we shouldn't allow resume for legacy orders b/c we lack the information necessary to restore to a previous state
      return false if state_events.empty? || state_events.last.previous_state.nil?
      true
    end

    def add_variant(variant, quantity = 1)
      current_item = contains?(variant)
      if current_item
        current_item.quantity += quantity
        current_item.save
      else
        current_item = LineItem.new(:quantity => quantity)
        current_item.variant = variant
        current_item.price   = variant.price

app/helpers/spree/admin/orders_helper.rb
module Spree
  module Admin
    module OrdersHelper
      # Renders all the txn partials that may have been specified in the extensions
      def render_txn_partials(order)
        @txn_partials.inject("") do |extras, partial|
          extras += render :partial => partial, :locals => { :payment => order }
        end
      end

      # Renders all the extension partials that may have been specified in the extensions
      def event_links
        links = []
        @order_events.sort.each do |event|
          if @order.send("can_#{event}?")
            links << button_link_to(t(event), fire_admin_order_url(@order, :e => event),
                                    { :method => :put, :confirm => t(:order_sure_want_to, :event => t(event)) })
          end
        end
        links.join('&nbsp;').html_safe
      end
    end
  end
end

app/helpers/spree/orders_helper.rb
module Spree
  module OrdersHelper

  end
end

app/views/spree/admin/orders/_add_product.html.erb
<div id="add-line-item" data-hook>
  <fieldset>
    <legend><%= t(:add_product) %></legend>
    <div style="float:left; width:65%; margin-right:5%;" data-hook="add_product_name">
      <%= label_tag :add_product_name, t(:name_or_sku) %>
      <%= text_field_tag :add_product_name, nil, :class => 'fullwidth title' %>
      <%= hidden_field_tag :add_variant_id %>
    </div>
    <div style="float:left; width:10%; margin-right:5%;" data-hook="add_quantity">
      <%= label_tag :add_quantity, t(:qty) %>
      <%= number_field_tag :add_quantity,  1, :min => 0, :class => 'fullwidth title' %>
    </div>
    <div style="float: left; width: 15%; padding-top: 17px;" data-hook="add_button">
      <%= link_to text_for_button_link(t(:add), :icon => 'add'),
            admin_order_line_items_url(@order),
            {:id => 'add_line_item_to_order', :class => 'button', 'data-update' => 'order-form-wrapper'} %>
    </div>

  </fieldset>
</div>

app/views/spree/admin/orders/_form.html.erb
<% if @line_item.try(:errors).present? %>
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @line_item } %>
<% end %>

<%= form_for @order, :url => admin_order_url(@order), :method => :put do |f| %>
  <%= f.hidden_field :number %>
  <table class="index">
    <tbody id="line-items">
      <tr data-hook="admin_order_form_line_items_headers">
        <th><%= t(:item_description) %></th>
        <th class="price"><%= t(:price) %></th>
        <th class="qty"><%= t(:qty) %></th>
        <th class="total"><span><%= t(:total) %></span></th>
        <th class="orders-actions" data-hook="admin_order_form_line_items_header_actions"></th>
      </tr>
      <%= f.fields_for :line_items do |li_form| %>
        <%= render :partial => 'spree/admin/orders/line_item', :locals => { :f => li_form } %>
      <% end %>
    </tbody>
    <tbody id="subtotal" data-hook="admin_order_form_subtotal">
      <tr id="subtotal-row">
        <td colspan="3"><b><%= t(:subtotal) %>:</b></td>
        <td class="total"><span><%= number_to_currency @order.item_total %></span></td>
        <td></td>
      </tr>
    </tbody>
    <tbody id="order-charges" data-hook="admin_order_form_adjustments">
      <% @order.adjustments.each do |adjustment| %>
        <tr>
          <td colspan="3"><strong><%= adjustment.label %></strong></td>
          <td class="total"><span><%= number_to_currency adjustment.amount %></span></td>
          <td></td>
        </tr>
      <% end %>
    </tbody>
    <tbody id="order-total" data-hook="admin_order_form_total">
      <tr>
        <td colspan="3"><b><%= t(:order_total) %>:</b></td>
        <td class="total"><span id="order_total"><%= number_to_currency @order.total %></span></td>
        <td></td>
      </tr>
    </tbody>
  </table>

  <p class="form-buttons" data-hook="admin_order_form_buttons">
    <%= button @order.complete? ? t(:update) : t(:continue) %>
    <%= t(:or) %> <%= link_to t('actions.cancel'), admin_orders_url %>
  </p>

<% end %>

<%= javascript_tag do -%>
  <%= render :partial => 'spree/admin/shared/update_order_state.js' %>
<% end -%>

<%= javascript_include_tag 'admin/orders/edit_form' %>

app/views/spree/admin/orders/_line_item.html.erb
<tr id="<%= dom_id(f.object) %>" data-hook="admin_order_form_line_item_row">
  <td width="300">
    <%=f.object.variant.product.name%> <%= "(#{f.object.variant.options_text}))" unless f.object.variant.option_values.empty? %>
  </td>
  <td valign="top" class="price"><%= number_to_currency f.object.price %></td>
  <td valign="top" class="qty"><%= f.number_field :quantity, :min => 0, :style => "width:30px;", :class => "qty" %></td>
  <td valign="top" class="total"><%= number_to_currency (f.object.price * f.object.quantity) %></td>
  <td data-hook="admin_order_form_line_item_actions">
    <%= link_to_delete f.object, {:url => admin_order_line_item_url(@order.number, f.object),
                                  :dataType => 'html',
                                  :success => "function(r){ $('#order-form-wrapper').html(r);}"},
                                  :title => "admin_delete_#{dom_id(@order)}" %>
  </td>
</tr>

app/views/spree/admin/orders/edit.html.erb
<%= csrf_meta_tags %>
<div class="order-links" data-hook="admin_order_edit_buttons">
  <div class="toolbar">
    <%= event_links %>
  </div>
  <div class="toolbar">
    <%= button_link_to t(:resend), resend_admin_order_url(@order), :method => :post, :icon => 'send-email' if @order.user %>
  </div>
</div>

<%= render :partial => 'spree/admin/shared/order_tabs', :locals => { :current => 'Order Details' } %>

<div data-hook="admin_order_edit_header">
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @order } %>
</div>

<%= render :partial => 'add_product' %>

<div data-hook="admin_order_edit_form">
  <div id="order-form-wrapper">
    <%= render :partial => 'form', :locals => { :order => @order } %>
  </div>
</div>

<% content_for :head do %>
  <%= javascript_tag 'var expand_variants = true;' %>
<% end %>

app/views/spree/admin/orders/history.html.erb
<%= render :partial => 'spree/admin/shared/order_tabs', :locals => { :current => 'History' } %>

<h2><%= t(:history) %></h2>

<table class="index">
  <tr data-hook="history_header">
    <th><%= t(:event) %></th>
    <th><%= t(:from_state) %></th>
    <th><%= t(:to_state) %></th>
    <th><%= t(:user) %></th>
    <th><%= "#{t('spree.date')}/#{t('spree.time')}" %></th>
  </tr>
  <% @order.state_events.sort.each do |event| %>
    <tr data-hook="history_row">
      <td><%=t("#{event.name}") if event.name.present? %></td>
      <td><%=t("#{event.name}_state#{'s' unless event.name == 'order'}.#{event.previous_state}") %></td>
      <td><%=t("#{event.name}_state#{'s' unless event.name == 'order'}.#{event.next_state}") %></td>
      <td><%=event.user.email if event.user %></td>
      <td><%=event.created_at.to_s(:date_time24) %></td>
    </tr>
  <% end %>
  <% if @order.state_events.empty? %>
    <tr data-hook="history_none">
      <td colspan="5"><%= t(:none_available) %></td>
    </tr>
  <% end %>
</table>

<%= button_link_to t(:continue), admin_orders_url %>

app/views/spree/admin/orders/index.html.erb
<div class='toolbar order-links'>
  <%= button_link_to t(:new_order), new_admin_order_url, :icon => 'add', :id => 'admin_new_order' %>
</div>

<%= render :partial => 'spree/admin/shared/order_sub_menu' %>

<h1><%= t(:listing_orders) %></h1>
<div style="text-align:right">
  <%= link_to 'Processing Orders','orders?order_status=processesing'%>
</div><br/>
<table class="index" id="listing_orders" data-hook>
  <thead>
    <tr data-hook="admin_orders_index_headers">
      <% if @show_only_completed %>
        <th><%= sort_link @search, :completed_at, t('activerecord.attributes.order.completed_at') %></th>
      <% else %>
        <th><%= sort_link @search, :created_at,   t(:order_date) %></th>
      <% end %>
      <th><%= sort_link @search, :number,         t(:order_number) %></th>
      <th><%= sort_link @search, :state,          t(:status) %></th>
      <th><%= sort_link @search, :payment_state,  t(:payment_state) %></th>
      <th><%= sort_link @search, :shipment_state, t(:shipment_state) %></th>
      <th><%= sort_link @search, :email,          t(:customer) %></th>
      <th><%= sort_link @search, :total,          t(:total) %></th>
      <th data-hook="admin_orders_index_header_actions"></th>
    </tr>
  </thead>
  <tbody>
  <% @orders.each do |order| %>
    <tr data-hook="admin_orders_index_rows">
      <td><%= l (@show_only_completed ? order.completed_at : order.created_at).to_date %></td>
      <td><%= link_to order.number, admin_order_path(order) %></td>
      <td><%= t("order_state.#{order.state.downcase}") %></td>
      <td><%= link_to t("payment_states.#{order.payment_state}"), admin_order_payments_path(order) if order.payment_state %></td>
      <td><%= link_to t("shipment_states.#{order.shipment_state}"), admin_order_shipments_path(order) if order.shipment_state %></td>
      <td><%= order.email %></td>
      <td><%= number_to_currency order.total %></td>
      <td class='actions' data-hook="admin_orders_index_row_actions">
        <%= link_to_edit_url edit_admin_order_path(order), :title => "admin_edit_#{dom_id(order)}" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= paginate @orders %>


<% content_for :sidebar do %>
  <div class="box" data-hook="admin_orders_index_search">
    <h3><%= t(:search) %></h3>
    <%= form_for [:admin, @search] do |f| %>
      <%= label_tag nil, t(:date_range) %><br />
      <div class="date-range-filter">
        <div class="left sub-field">
          <%= f.text_field :created_at_greater_than, :class => 'datepicker' %><br />
          <%= label_tag nil, t(:start), :class => 'sub' %>
        </div>
        <div class="right sub-field">
          <%= f.text_field :created_at_less_than, :class => 'datepicker' %><br />
          <%= label_tag nil, t(:stop), :class => 'sub' %>
        </div>
      </div>

      <p><%= label_tag nil, t(:status) %><br />
      <%= f.select :state_equals, Spree::Order.state_machines[:state].states.collect {|s| [t("order_state.#{s.name}"), s.value]}, {:include_blank => true} %></p>

      <p>
        <%= label_tag nil, t(:order_number) %><br />
        <%= f.text_field :number_like, :size => 25 %>
      </p>
      <p>
        <%= label_tag nil, t(:email) %><br />
        <%= f.text_field :email_like, :size => 25 %>
      </p>
      <p>
        <%= label_tag nil, t(:first_name_begins_with) %><br />
        <%= f.text_field :bill_address_firstname_starts_with, :size => 25 %>
      </p>
      <p>
        <%= label_tag nil, t(:last_name_begins_with) %><br />
        <%= f.text_field :bill_address_lastname_starts_with, :size => 25 %>
      </p>
      <p>
        <%= f.check_box :completed_at_is_not_null, {:checked => @show_only_completed}, '1', '' %>
        <%= label_tag nil, t(:show_only_complete_orders) %>
      </p>
      <div data-hook="admin_orders_index_search_buttons">
        <p><%= button t(:search) %></p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/spree/admin/orders/new.html.erb
<%= render :partial => 'spree/admin/shared/order_tabs', :locals => { :current => 'Order Details' } %>
<%= csrf_meta_tags %>

<div data-hook="admin_order_new_header">
  <h2><%= t(:new_order) %></h2>
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @order } %>
</div>

<%= render :partial => 'add_product' %>

<div data-hook="admin_order_new_form">
  <div id="order-form-wrapper">
    <%= render :partial => 'form' %>
  </div>
</div>

<% content_for :head do %>
  <%= javascript_tag 'var expand_variants = true;' %>
<% end %>

app/views/spree/admin/orders/show.html.erb
<div class="toolbar order-links" data-hook="admin_order_show_buttons">
  <%= button_link_to t(:cancel), fire_admin_order_url(@order.number, {:e => "cancel"}), :icon => 'delete', :confirm => t(:are_you_sure) if @order.can_cancel? %>
  <%= button_link_to t(:edit), edit_admin_order_url(@order.number), :icon => 'edit' %>
</div>

<%= render :partial => 'spree/admin/shared/order_tabs', :locals => { :current => 'Order Details' } %>

<div data-hook="admin_order_show_addresses">
  <% if @order.bill_address %>
    <div class="adr">
      <h4><%= t(:bill_address) %></h4>
      <%= render :partial => 'spree/admin/shared/address', :locals => { :address => @order.bill_address } %>
    </div>
  <% end %>
  <% if @order.ship_address %>
    <div class='adr'>
      <h4><%= t(:ship_address) %></h4>
      <%= render :partial => 'spree/admin/shared/address', :locals => { :address => @order.ship_address } %>
    </div>
    <% end %>
  <hr />
</div>

<div data-hook="admin_order_show_details">
  <%= render :partial => 'spree/admin/shared/order_details', :locals => { :order => @order } %>
</div>